### ISSUE TITLE
Trait to provide Docker Image Version 2 Schema 2 media type equivalents

### ISSUE THREAD

**Issue by nokome** [containers/oci-spec-rs#105]
First, thank you for `oci-spec-rs` 🙏🏽 , I've been using it recently in Stencila to [build OCI images for executable documents](https://github.com/stencila/stencila/pull/1457) and it have been proving really useful!

One of the issues I found was that Docker registry (and perhaps Fly.io's infrastructure) didn't recognize / didn't work with the `application/vnd.oci.image.manifest.v1+json` media type. My workaround was to use `application/vnd.docker.distribution.manifest.v2+json` instead and all my problems went away 🙂 .

I abstracted this into a trait so I could continue to use `oci_spec::image::MediaType` in most of my code and only call `to_docker_v2s2()` in places I needed it (instead of strings).

Anyway, I thought this might me more generally useful, and would be happy to submit a PR if it is wanted. The code is just:

```rust
use oci_spec::image::MediaType;

/**
 * Get the [Docker Image Manifest V2, Schema 2](https://docs.docker.com/registry/spec/manifest-v2-2/)
 * media type equivalent for an [OCI Media Type](https://github.com/opencontainers/image-spec/blob/main/media-types.md).
 *
 * This trait may be necessary for compatibility with tools that do not recognize the OCI Media Types.
 * Where a [`MediaType`] is expected (e.g. the `media_type` method of builders) you can use
 * `MediaType::ImageManifest.to_docker_v2s2()?` instead.
 *
 * Not all OCI Media Types have an equivalent Docker V2S2 Media Type. In those cases, `to_docker_v2s2` will error.
 */
pub trait ToDockerV2S2 {
    fn to_docker_v2s2(&self) -> Result<&str, std::fmt::Error>;
}

impl ToDockerV2S2 for MediaType {
    fn to_docker_v2s2(&self) -> Result<&str, std::fmt::Error> {
        Ok(match self {
            Self::ImageIndex => "application/vnd.docker.distribution.manifest.list.v2+json",
            Self::ImageManifest => "application/vnd.docker.distribution.manifest.v2+json",
            Self::ImageConfig => "application/vnd.docker.container.image.v1+json",
            Self::ImageLayerGzip => "application/vnd.docker.image.rootfs.diff.tar.gzip",
            _ => return Err(std::fmt::Error),
        })
    }
}
```

**Comment by saschagrunert** [comment]
Yeah this sounds like a reasonable addition, feel free to go ahead and submit a PR. :blush:

**Comment by utam0k** [comment]
I agree with @saschagrunert. It sounds good.
