### ISSUE TITLE
A youki member to join containers member

### ISSUE THREAD

**Issue by utam0k** [containers/oci-spec-rs#110]
Hi, @rhatdan, @saschagrunert 

I'd like to invite @Furisto to the containers member. WDYT?
He is a active contributor of  `containers/oci-spec-rs`, `containers/youki` and `containers/containrs . He is youki's [number one contributor](https://github.com/containers/youki/graphs/contributors). Of course, he has interested in containers member. There is no particular change, but I do not think there is any room for denial in my opinion for him to become a member of this group.

**Comment by saschagrunert** [comment]
+1 from my side

**Comment by utam0k** [comment]
Hi, @rhatdan. WDYT?

**Comment by Furisto** [comment]
Thank you everyone! 🙏

**Comment by utam0k** [comment]
@lsm5 Thanks!! Nothing for now.
