### ISSUE TITLE
Add Time namespace

### ISSUE THREAD

**Issue by lengrongfu** [containers/oci-spec-rs#121]
https://github.com/opencontainers/runtime-spec/blob/main/config-linux.md#namespaces

**time** the container will be able to have its own clocks.

Can I add Time namespace?

**Comment by saschagrunert** [comment]
@lengrongfu yes sure we can support the time namespace. Do you want to propose it as PR?

**Comment by lengrongfu** [comment]
> @lengrongfu yes sure we can support the time namespace. Do you want to propose it as PR?

Yes.
