### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by yihuaf** [containers/oci-spec-rs#132]
@utam0k I don't think I have access to this repo, so we need your help to cut a new release. Specifically, to fix https://github.com/containers/youki/issues/2022, we will need this https://github.com/containers/oci-spec-rs/pull/125.

Let me know if there is anything I can help with.

**Comment by saschagrunert** [comment]
@utam0k we tagged 6de57371cab7b505a4a96f3300295e0d50ccc778 as v0.6.1 but it shoud be d0d41db14e705803dde0cbc460bd73a17e7d2e9d, because it has not the `-dev` in the `VERSION` constants. Not sure how much this is a problem, though.

**Comment by utam0k** [comment]
@saschagrunert I did https://github.com/containers/oci-spec-rs/commit/d0d41db14e705803dde0cbc460bd73a17e7d2e9d at first, but for some reason that commit tree didn't include the new changes.
https://github.com/containers/oci-spec-rs/commits/d0d41db14e705803dde0cbc460bd73a17e7d2e9d

I've already posted it on crates.io, so I'll respond to any issues that come up. Sorry about that.

**Comment by saschagrunert** [comment]
No worries, I think we're still good.
