### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by yihuaf** [containers/oci-spec-rs#137]
Also can we bump the minor version `0.7.x` since the spec may contain breaking changes. CC @saschagrunert @utam0k

Side note, do you guys think it will be helpful to add me to this repo so I can help cut a release?

**Comment by saschagrunert** [comment]
Hey, if you want to maintain it then we'd be happy to have you helping us. What do you think @utam0k?

**Comment by utam0k** [comment]
@saschagrunert :+1:
How about making this repository maintained by youki team?

**Comment by saschagrunert** [comment]
Done updating the permissions :+1: 

@yihuaf please follow the release guides for cutting a new release: https://github.com/containers/oci-spec-rs/blob/main/release.md

**Comment by utam0k** [comment]
@saschagrunert Thanks 🙏

**Comment by utam0k** [comment]
@yihuaf @saschagrunert I have published it to crates.io
