### ISSUE TITLE
Missing builder for the oci-layout file

### ISSUE THREAD

**Issue by ariel-miculas** [containers/oci-spec-rs#141]
It's defined in the specification as a mandatory file, as part of the image layout:
https://github.com/opencontainers/image-spec/blob/main/image-layout.md#oci-layout-file
I didn't find a way to generate it using the library.

**Comment by saschagrunert** [comment]
@ariel-miculas ah yeah, do you plan to add it by proposing a PR? :slightly_smiling_face:

**Comment by ariel-miculas** [comment]
Yes, I could add an OciLayoutBuilder if that sounds right to you.

**Comment by saschagrunert** [comment]
Thank you @ariel-miculas! :pray:
