### ISSUE TITLE
Fix spec inconsistencies

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-spec-rs#17]
We're using some types in youki which are not part of the spec: 

https://github.com/containers/oci-spec-rs/blob/26decc800ad1e0848d628c420670a8528da56998/src/runtime/linux.rs#L512-L522

We should find out where they belong and if we should remove/move them.

**Comment by Furisto** [comment]
- disable_oom_killer is part of [memory ](https://github.com/opencontainers/runtime-spec/blob/master/config-linux.md#memory)
- oom_score_adj is part of [process](https://github.com/opencontainers/runtime-spec/blob/master/config.md#linux-process) 
- freezer was added as part of [this PR](https://github.com/containers/youki/pull/93/files) (needs to be removed)

I can send a PR later today that fixes this inconsistencies.
