### ISSUE TITLE
Enhance Enum Types with String Conversion Capabilities

### ISSUE THREAD

**Issue by Apokleos** [containers/oci-spec-rs#173]
For certain enum types, we need to convert them to their corresponding strings, or be able to map a given string to the corresponding enum type. However, many enum types currently lack these helper functions. To achieve these two capabilities, we would need to implement:
```rust
impl std::fmt::Display for EnumStruct {}
impl std::str::FromStr for EnumStruct {}
```
Introduce capabilities that effectively reduce code duplication and facilitate rapid conversion.

**Comment by utam0k** [comment]
Thanks. Please give us some specific examples.

**Comment by saschagrunert** [comment]
Hm, maybe we can make that an additional feature and use something like [strum](https://docs.rs/strum/latest/strum/) for it.

**Comment by Apokleos** [comment]
> Thanks. Please give us some specific examples.



> Thanks. Please give us some specific examples.
>

Thx @utam0k for your reply. some Enum types involved as below: 
- lack conversion for both direction: Arch, LinuxSeccompAction, LinuxSeccompFilterFlag, LinuxSeccompOperator in linux.rs
- lack one direction conversion: LinuxDeviceType, LinuxNamespaceType in linux.rs
- Capability in the file capability.rs

**Comment by Apokleos** [comment]
> Hm, maybe we can make that an additional feature and use something like [strum](https://docs.rs/strum/latest/strum/) for it.
>
Thx @saschagrunert, IMO, `Strum` maybe be a good way for lack both directions conversion's cases. But I don't know whether it's a good choice for some cases which already implement one direction conversion's cases such as LinuxDeviceType, it has as_str() to do conversion from Enum to String

**Comment by saschagrunert** [comment]
> > Hm, maybe we can make that an additional feature and use something like [strum](https://docs.rs/strum/latest/strum/) for it.
> 
> Thx @saschagrunert, IMO, `Strum` maybe be a good way for lack both directions conversion's cases. But I don't know whether it's a good choice for some cases which already implement one direction conversion's cases such as LinuxDeviceType, it has as_str() to do conversion from Enum to String

Yeah that's true, so we may end up doing all by hand.

**Comment by utam0k** [comment]
> But I don't know whether it's a good choice for some cases which already implement one direction conversion's cases such as LinuxDeviceType, it has as_str() to do conversion from Enum to String

I'm not an expert on strum, but I wonder if strum generates the `as_str` method. `as_str` is the original method for `LinuxDeviceType`. If not, Strum looks good to me.
https://github.com/containers/oci-spec-rs/blob/da761c536a9ed4ca9f21b9d6ca96d5d34371733c/src/runtime/linux.rs#L223-L234
