### ISSUE TITLE
Release Cycle and Next release 

### ISSUE THREAD

**Issue by Apokleos** [containers/oci-spec-rs#176]
Hi @utam0k @saschagrunert Thx you first for helping me review and merge PRs. 
I'd like to know the release cycle for oci-spec-rs and when the next release is scheduled.

**Comment by saschagrunert** [comment]
Hey, we probably want to get https://github.com/containers/oci-spec-rs/pull/174 in and can then work on a new release.

**Comment by saschagrunert** [comment]
v0.6.6 is released and published:
https://github.com/containers/oci-spec-rs/releases/tag/v0.6.6
https://crates.io/crates/oci-spec/0.6.6
