### ISSUE TITLE
Should we take string "mount" and "network" into account for LinuxNamespaceType::Mount and LinuxNamespaceType::Network ?

### ISSUE THREAD

**Issue by Apokleos** [containers/oci-spec-rs#186]
As the title described, some secanios might not using "mnt" or "net" for LinuxNamespaceType::Mount and LinuxNamespaceType::Network, but using "mount" and "network". In such case, we can not use LinuxNamespaceType::try_from(namespace) to get enum LinuxNamespaceType from "mount" or "network", as in such cases, errors occur.

For these cases, I propose that add 
```rust
- "mnt" => Ok(LinuxNamespaceType::Mount),
+ "mount" | "mnt" => Ok(LinuxNamespaceType::Mount),
...
- "net" => Ok(LinuxNamespaceType::Network),
+ "network" | "net" => Ok(LinuxNamespaceType::Network),
```

Thx @saschagrunert @utam0k Looking forward to your information.

**Comment by saschagrunert** [comment]
Is the OCI spec in the same way flexible? I'm wondering which use case you have.

**Comment by Apokleos** [comment]
> Is the OCI spec in the same way flexible? I'm wondering which use case you have.
>
Thx @saschagrunert ! 
In my case, I need converse to `LinuxNamespace::Mount` from string namespace type `"mount"` but not string `"mnt"`  and similar the case of string type `"network"` to `LinuxNamespace::Network`.
IMO, no matter "mount" or "mnt", "network" or "net" to `LinuxNamespace::Mount` or `LinuxNamespaceNetwork`, it will not break or affect the existing Enum LinuxNamespace, as they are conversed by `LinuxNamespace::try_from(ns_str)?`

**Comment by Apokleos** [comment]
> Is the OCI spec in the same way flexible?
>
In [spec-go](https://github.com/opencontainers/runtime-spec/blob/701738418b9555d5213337a0991fd0ffd6c37808/specs-go/config.go#L276), the LinuxNamespace::Mount is defined with string "mount" and LinuxNamespace::Network  with string "network". With this aspect, we'd better align it with definitions in spec-go ?
