### ISSUE TITLE
Disccuss: Regex and once_cell with high version might cause compatibility issues

### ISSUE THREAD

**Issue by Apokleos** [containers/oci-spec-rs#190]
Hi @saschagrunert @utam0k 
I am working migrate the oci-spec-rs latest version to my project. and encounted compatibility issues then I analysis it and found that regex and once_cell are the root cause. 

I noticed that there's a [PR#178](https://github.com/containers/oci-spec-rs/pull/178) which introduces ExecAffinityCPU into oci-spec-rs, actually great work! 

I want to talk about whether we need such high version regex and once_cell, as some projects depending on oci-spec-rs might not introduce such high version regex and once_cell.

Thx

**Comment by keisku** [comment]
FYI: https://github.com/containers/oci-spec-rs/pull/178/commits/73c974022d784d562d8400af0c8bd844fb1d7cf2 doesn't require `regex` and `once_cell` dependencies. We didn't apply this way because of this [benchmark result](https://github.com/containers/oci-spec-rs/pull/178#issuecomment-2208951180).

**Comment by Apokleos** [comment]
> FYI: [73c9740](https://github.com/containers/oci-spec-rs/commit/73c974022d784d562d8400af0c8bd844fb1d7cf2) doesn't require `regex` and `once_cell` dependencies. We didn't apply this way because of this [benchmark result](https://github.com/containers/oci-spec-rs/pull/178#issuecomment-2208951180).
>
Hi @keisu Thx for your reply. 
I found the regex and once_cell introduced in [Cargo.toml](https://github.com/containers/oci-spec-rs/blob/1b542391261a38e0f5cfb0dd37a418a49c00f0b9/Cargo.toml#L35)

**Comment by Apokleos** [comment]
> FYI: [73c9740](https://github.com/containers/oci-spec-rs/commit/73c974022d784d562d8400af0c8bd844fb1d7cf2) doesn't require `regex` and `once_cell` dependencies. We didn't apply this way because of this [benchmark result](https://github.com/containers/oci-spec-rs/pull/178#issuecomment-2208951180).
>
If I understand it correctly, the regex and once_cell should be not in the Cargo.toml, right ?

**Comment by Apokleos** [comment]
Hi @keisku @saschagrunert @utam0k FYI!  thx

**Comment by utam0k** [comment]
> If I understand it correctly, the regex and once_cell should be not in the Cargo.toml, right ?

Why so? Since we don't need the specific and latest `regex` and `once_cell`, how about we specify the minimal versions we need in `Cargo.toml` instead of them?
https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements

**Comment by Apokleos** [comment]
> > If I understand it correctly, the regex and once_cell should be not in the Cargo.toml, right ?
> 
> Why so? Since we don't need the specific and latest `regex` and `once_cell`, how about we specify the minimal versions we need in `Cargo.toml` instead of them? https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements
>
Thx @utam0k for your reply.  and sorry for misunderstand of it. And have a deep learn about the PR with many commits, I got that 
the commits: [introducing regex ](https://github.com/containers/oci-spec-rs/commit/18a85b213f5ae83dc1758da0a401b3f7b06df166) and [introducing once_cell](https://github.com/containers/oci-spec-rs/commit/e01daa1ec34990469854e4e3d7d4051cbe9dce55) and then [in this commit avoid using regex and once_cell](https://github.com/containers/oci-spec-rs/commit/73c974022d784d562d8400af0c8bd844fb1d7cf2) and then [in this commit](https://github.com/containers/oci-spec-rs/commit/d066e9c9d2254d4eb2f8268ebf2f8ddfb08cf99b) do revert to keep origin idea of introducing regex and once_cell.  So regex and once_cell introduced, right ?

**Comment by Apokleos** [comment]
@utam0k 

> > If I understand it correctly, the regex and once_cell should be not in the Cargo.toml, right ?
> 
> 
> how about we specify the minimal versions we need in `Cargo.toml` instead of them? https://doc.rust-> lang.org/cargo/reference/specifying-dependencies.html#tilde-requirements
> 
Yeah, good idea. SGTM!

**Comment by utam0k** [comment]
> Thx @utam0k for your reply. and sorry for misunderstand of it. And have a deep learn about the PR with many commits, I got that
the commits: [introducing regex ](https://github.com/containers/oci-spec-rs/commit/18a85b213f5ae83dc1758da0a401b3f7b06df166)and [introducing once_cell](https://github.com/containers/oci-spec-rs/commit/e01daa1ec34990469854e4e3d7d4051cbe9dce55) and then [in this commit avoid using regex and once_cell](https://github.com/containers/oci-spec-rs/commit/73c974022d784d562d8400af0c8bd844fb1d7cf2) and then [in this commit](https://github.com/containers/oci-spec-rs/commit/d066e9c9d2254d4eb2f8268ebf2f8ddfb08cf99b) do revert to keep origin idea of introducing regex and once_cell. So regex and once_cell introduced, right ?

Oh, I see. This is certainly misleading. 

> Yeah, good idea. SGTM!

Do you have a chance to contribute to it? If not, I'll be looking for those who are interested in first-contributing to oci-spec-rs.

**Comment by Apokleos** [comment]
> > Thx @utam0k for your reply. and sorry for misunderstand of it. And have a deep learn about the PR with many commits, I got that
> > the commits: [introducing regex ](https://github.com/containers/oci-spec-rs/commit/18a85b213f5ae83dc1758da0a401b3f7b06df166)and [introducing once_cell](https://github.com/containers/oci-spec-rs/commit/e01daa1ec34990469854e4e3d7d4051cbe9dce55) and then [in this commit avoid using regex and once_cell](https://github.com/containers/oci-spec-rs/commit/73c974022d784d562d8400af0c8bd844fb1d7cf2) and then [in this commit](https://github.com/containers/oci-spec-rs/commit/d066e9c9d2254d4eb2f8268ebf2f8ddfb08cf99b) do revert to keep origin idea of introducing regex and once_cell. So regex and once_cell introduced, right ?
> 
> Oh, I see. This is certainly misleading.
> 
> > Yeah, good idea. SGTM!
> 
> Do you have a chance to contribute to it? If not, I'll be looking for those who are interested in first-contributing to oci-spec-rs.
>
Yeah, appreciated! I will enhance it with your suggest no later than tomorrow, is that Ok?

**Comment by utam0k** [comment]
> Yeah, appreciated! I will enhance it with your suggest no later than tomorrow, is that Ok?

Sure. But I'm going to be unavailable for the next couple of days.

**Comment by Apokleos** [comment]
> > Yeah, appreciated! I will enhance it with your suggest no later than tomorrow, is that Ok?
> 
> Sure. But I'm going to be unavailable for the next couple of days.
>
Ok, I first handle this issue before you are unavalible.

**Comment by kpcyrd** [comment]
The current workaround breaks `cargo outdated -R`:

```
% cargo outdated -R
error: failed to select a version for `regex`.
    ... required by package `oci-spec v0.7.0`
    ... which satisfies dependency `oci-spec = "^0.7.0"` of package `sh4d0wup v0.9.3 (/tmp/cargo-outdatedYX4PxY)`
versions that meet the requirements `~1.10.5` are: 1.10.6, 1.10.5

all possible versions conflict with previously selected packages.

  previously selected package `regex v1.11.0`
    ... which satisfies dependency `regex = "^1.11.0"` of package `sh4d0wup v0.9.3 (/tmp/cargo-outdatedYX4PxY)`

failed to select a version for `regex` which could resolve this conflict
```

Changing from oci-spec 0.6 to 0.7 forces a downgrade of the regex crate in my project:
```
% cargo update
    Updating crates.io index
     Locking 2 packages to latest compatible versions
    Updating oci-spec v0.6.7 -> v0.7.0
 Downgrading regex v1.11.0 -> v1.10.6 (latest: v1.11.0)
note: pass `--verbose` to see 72 unchanged dependencies behind latest
```

Please do not use the tilde operator like this, specify the minimum version you want to require (or simply `1`) without any prefix and cargo is going to select a semver compatible version for you automatically.
