### ISSUE TITLE
Add opt-in support for more validation

### ISSUE THREAD

**Issue by cgwalters** [containers/oci-spec-rs#201]
I'm working on code using this crate, and one thing I am hitting up against is that the types defined here are quite loose, often accepting arbitrary `String` for fields.

For example, this test fails:

```
diff --git a/src/image/descriptor.rs b/src/image/descriptor.rs
index 5e36e372c..d731144ad 100644
--- a/src/image/descriptor.rs
+++ b/src/image/descriptor.rs
@@ -178,4 +178,15 @@ mod tests {
             MediaType::Other("application/spdx+json".to_string())
         );
     }
+
+    #[test]
+    fn test_deserialize_not_a_checksum() {
+        let descriptor_str = r#"{
+            "mediaType": "application/vnd.oci.image.manifest.v1+json",
+            "digest":"/usr/bin/bash",
+            "size":769,
+            "annotations":{"org.opencontainers.image.created": "2023-10-11T22:37:26Z"},
+            "artifactType":"application/spdx+json"}"#;
+        assert!(serde_json::from_str::<Descriptor>(descriptor_str).is_err());
+    }
 }
```

i.e. I just put `/usr/bin/bash` in the descriptor digest. 

I'd like us to consider doing a semver break where we add e.g. a `pub struct Digest(String)` that has verified the syntax of the digest, etc.

(Also while we're here, it's annoying that `size()` is `i64` - why? Sizes can't be negative...so let's just fix that)

Opinions?

**Comment by cgwalters** [comment]
https://github.com/containers/oci-spec-rs/pull/203 and https://github.com/containers/oci-spec-rs/pull/202 will address my major pain points, but we should probably think about whether there are other potential things to improve in a semver break around these lines.

**Comment by saschagrunert** [comment]
@cgwalters is this done?

**Comment by cgwalters** [comment]
Well...a crude regex search for `:.*String` turns up a lot of things that *could* be more strictly parsed+validated, e.g.

```
    /// Entries are in the format of VARNAME=VARVALUE. These
    /// values act as defaults and are merged with any
    /// specified when creating a container.
    #[serde(skip_serializing_if = "Option::is_none")]
    env: Option<Vec<String>>,
```

And the ports too? But...eh.
