### ISSUE TITLE
Add distribution spec

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-spec-rs#21]
The [OCI distribution spec](https://github.com/opencontainers/distribution-spec) could be also part of this repository. Do you have thoughts on that?

**Comment by utam0k** [comment]
I think we can mix it up too. The default is good for both runtime and image; however, I'm glad I can use features to introduce only the one I want.

**Comment by utam0k** [comment]
The OCI distribution spec is a specification managed by OCI, so it is not surprising it is supported by the name of this crate.
