### ISSUE TITLE
Release v0.7.0

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-spec-rs#210]
Placeholder issue to remind us releasing the next version.

**Comment by musaprg** [comment]
I'm also wondering when the new release will be ready. I'd like to use https://github.com/containers/oci-spec-rs/pull/184 in https://github.com/containers/youki/pull/2837.

**Comment by flavio** [comment]
The tag has been created and the crate can be consumed from `crates.io`, however https://docs.rs/oci-spec/latest/oci_spec/ is still pointing to `v0.6.8`

**Comment by saschagrunert** [comment]
I think docs.rs need a rebuild on their end to catch-up with the latest version.
