### ISSUE TITLE
Add prow support

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-spec-rs#226]
Are we all happy to add prow support to this project?

**Comment by cgwalters** [comment]
Maybe? Would it run CI tests? Would it also be the merge bot?

**Comment by saschagrunert** [comment]
@cgwalters in the first place the merge bot, we can add tests later on if we want.

**Comment by cgwalters** [comment]
I'm not actively opposed, but nowadays GitHub has an integrated auto-merge and merge queue even functionality. Having Prow just for that IMO adds another point of failure unnecessarily.

I do know that other projects in this organization use Prow, and there is crossover between their contributors and here. But others in this organization don't.

What I personally find most valuable about Prow is being able to do Kubernetes things in CI, but we don't really need that for this project AFAIK.

**Comment by utam0k** [comment]
> I'm not actively opposed, but nowadays GitHub has an integrated auto-merge and merge queue even functionality. Having Prow just for that IMO adds another point of failure unnecessarily.
> 
> I do know that other projects in this organization use Prow, and there is crossover between their contributors and here. But others in this organization don't.
> 
> What I personally find most valuable about Prow is being able to do Kubernetes things in CI, but we don't really need that for this project AFAIK.

I have the same option. I don't strongly disagree, but I'd like to know why. We are used to using prow, but it isn't for new contributors.

**Comment by saschagrunert** [comment]
Sounds good to me, let's keep it as-is for now.
