### ISSUE TITLE
Replace anyhow

### ISSUE THREAD

**Issue by Furisto** [containers/oci-spec-rs#26]
The anyhow result type appears in our public api, which is not ideal. Should we switch to thiserror or write our own error types? What do you think?

**Comment by humancalico** [comment]
The anyhow README mentions

> Use Anyhow if you don't care what error type your functions return, you just want it to be easy. This is common in application code. Use thiserror if you are a library that wants to design your own dedicated error type(s) so that on failures the caller gets exactly the information that you choose.

So it makes sense to use thiserror for our use-case.

**Comment by saschagrunert** [comment]
Yeah I agree, having own error types seems reasonable. :+1:

**Comment by Furisto** [comment]
I will take care of it.
