### ISSUE TITLE
Capability handling

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-spec-rs#27]
I'm wondering if we want to rely on [caps-rs](https://github.com/lucab/caps-rs) or switch to our own implementation. In theory we would only need the types with the serialization functionality. For example, we did the same in `containrs`: https://github.com/cri-o/containrs/blob/master/src/capability.rs

I still see a benefit of having it in a dedicated crate, so I'm wondering what your thoughts are.

**Comment by utam0k** [comment]
I agree with you :+1:

**Comment by saschagrunert** [comment]
So, do we wanna add our own caps types?

**Comment by utam0k** [comment]
> So, do we wanna add our own caps types?

I think it's good. This crate should only provide the type, and dependency on the crate to operate should be eliminated.
