### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by saschagrunert** [containers/oci-spec-rs#3]
I think we should set up a basic CI pipeline for the crate, which does:

- [x] build
- [x] unit test including code coverage
- [x] clippy lint
- [x] rustfmt
- [x] build docs and push to gh-pages branch
- [x] crates.io publishing

**Comment by utam0k** [comment]
What about the release flow to crate.io?

**Comment by saschagrunert** [comment]
> What about the release flow to crates.io?
> https://crates.io/

Which crate name do we wanna choose?

**Comment by utam0k** [comment]
It seems that `oci` already several crates. `oci_spec` is the best, however, I think `_` and `-` might be misunderstood, so I think `oci_spec_rs` is fine. What do you think?
https://crates.io/search?page=1&per_page=10&q=oci

It seems that `_` is preferred over `-`.
https://github.com/rust-lang/api-guidelines/discussions/29#discussioncomment-233428

**Comment by saschagrunert** [comment]
oci_spec already exists: https://crates.io/crates/oci_spec

I'm also in favor of `oci_spec_rs`.

**Comment by utam0k** [comment]
@saschagrunert I am very much in favor of cooperation. I'm sure the knowledge of this author will be put to great use.
However, I can't really imagine how we can cooperate. What kind of cooperation do you imagine?

**Comment by saschagrunert** [comment]
> @saschagrunert I am very much in favor of cooperation. I'm sure the knowledge of this author will be put to great use.
> However, I can't really imagine how we can cooperate. What kind of cooperation do you imagine?

It looks like that the initial crate got no update since 2 years. For example we would also need the image (and maybe artifact) spec beside the runtime spec.

So asking directly @smiyaguchi, do you see a way that we can reuse the crate name and merge both positive sides of the repositories?

**Comment by utam0k** [comment]
The image spec could certainly be integrated 👍

**Comment by smiyaguchi** [comment]
@saschagrunert Thank you for contacting me.
> do you see a way that we can reuse the crate name and merge both positive sides of the repositories?

I have never repurposed a crate before, so I don't know if it would work, but would you like me to add the owner to the oci-spec crate?

I think this is a great project and I would be happy to help in any way I can.
If you have any other ideas, please let me know.

**Comment by saschagrunert** [comment]
> @saschagrunert Thank you for contacting me.
> 
> > do you see a way that we can reuse the crate name and merge both positive sides of the repositories?
> 
> I have never repurposed a crate before, so I don't know if it would work, but would you like me to add the owner to the oci-spec crate?

This would be wonderful, thank you so much! :heart: (please add @utam0k, too)

> I think this is a great project and I would be happy to help in any way I can.
> If you have any other ideas, please let me know.

Thank you! Yeah the integration of other parts of the spec is definitely a goal. Feel free to mention if you notice any gaps between your implementation and this one. We're happy to take the advantage of both.

**Comment by utam0k** [comment]
Thank you for responding. Let's work together :handshake:

**Comment by saschagrunert** [comment]
Closing since the crate name point has been resolved.
