### ISSUE TITLE
Release 0.5.2

### ISSUE THREAD

**Issue by guni1192** [containers/oci-spec-rs#72]
This PR (#69 ) is bug fix LinuxPids.
We want to use the oci-spec-rs with this patch in youki.
Can you please release a version that incorporates this PR?

**Comment by utam0k** [comment]
@guni1192 Sorry, we can't release it because another maintainer who has write access is on vacation. We hope to release it by the end of next month.

**Comment by saschagrunert** [comment]
It's out now: https://crates.io/crates/oci-spec/0.5.2
