### ISSUE TITLE
even with setters, the builder pattern has large ergonomic hits

### ISSUE THREAD

**Issue by cgwalters** [containers/oci-spec-rs#86]
I know the builder pattern has been debated many times here.  This is quite similar to https://github.com/containers/oci-spec-rs/pull/74

It was concluded to [add setters](https://github.com/containers/oci-spec-rs/pull/80).  But, I still see two (related) issues:

## Fallible construction and required fields

Using `.build()` is a fallible operation because some fields are required.  This forces use of `unwrap()`.  I think instead we should add methods that take all the required fields to start.  This is much like how `std::process::Command::new()` requires a single string - the binary to run.  Then converting the builder into a final struct can be an infallible operation. 

What tripped me up twice is that it's needed to manually set `.schema_version()` e.g. on `ImageManifest`.  I caught this in unit tests (so not the end of the world or anything) but in Rust we can do this stuff at compile time with the type system.

## Mutation requires deep-copying

An operation like appending a layer requires deep-copying 3 `Vec` instances - the [layers Vec](https://docs.rs/oci-spec/latest/oci_spec/image/struct.ImageManifest.html#method.layers) and the rootfs and history in the config struct.

This isn't terrible, but WDYT about adding a method like this?

```
diff --git a/src/image/manifest.rs b/src/image/manifest.rs
index 7fbcef49..d4a09510 100644
--- a/src/image/manifest.rs
+++ b/src/image/manifest.rs
@@ -164,6 +164,10 @@ impl ImageManifest {
     pub fn to_writer_pretty<W: Write>(&self, writer: &mut W) -> Result<()> {
         to_writer(&self, writer, true)
     }
+
+    pub fn push_layer(&mut self, blob: Descriptor) {
+        self.layers.push(blob)
+    }
 }
 
 #[cfg(test)]
```

Or to summarize, short term I think I'm arguing to keep the builder pattern, but add helper methods.

Longer term, it's not really clear to me that all this builder stuff is adding significant value over just having a crate with struct types where all the fields are `pub`, and helper methods on top of that.

**Comment by yihuaf** [comment]
Can we generate mut setter for this? Adding helper is good only if it achieves something more than just the setter IMO.

> Longer term, it's not really clear to me that all this builder stuff is adding significant value over just having a crate with struct types where all the fields are pub, and helper methods on top of that.

Then it will be another round of breaking change LOL.

**Comment by cgwalters** [comment]
PR in https://github.com/containers/oci-spec-rs/pull/87

**Comment by cgwalters** [comment]
Well, let's call this fixed for now.  We can just add more mut setters if anyone needs them.

Can we turn the crank on a new release?  I now depend on this in the latest ostree code.

**Comment by saschagrunert** [comment]
Yep, sure: https://github.com/containers/oci-spec-rs/pull/92
