### ISSUE TITLE
`ImageConfiguration::default()` is a trap

### ISSUE THREAD

**Issue by cgwalters** [containers/oci-spec-rs#88]
https://github.com/containers/oci-spec-rs/blob/2440343d3433762c359c7a096648ca685f8ddd97/src/image/config.rs#L189

We can't just assume the world is Linux/x86_64 by default.  (And definitely not x86_64 :wink:  )

I have this code in ostree-rs-ext:
https://github.com/ostreedev/ostree-rs-ext/blob/bb4423d5af109cf6268e91c77cc4c9ca850e579a/lib/src/container/ocidir.rs#L26

WDYT about having this code in this crate?  Alternatively, I think we should drop the `default()` method.

Or in theory, these helper methods could go in some other containers/ related crate?  I hesitate at the overhead for that.  Maybe we introduce a `oci_spec::util` module?

**Comment by cgwalters** [comment]
I think I'm really arguing for one of:

1. changing `ImageConfiguration::default()` to default to the current process' OS and architecture
2. Dropping `default()` and adding a new `ImageConfiguration::default_this_platform_arch()` or so
3. Dropping `default()` and pointing users to helper methods that give suitable values to pass to `ImageConfigurationBuilder::arch().platform()`

I think I like the number 2 the best.

**Comment by cgwalters** [comment]
Definitely.  But having a `::default()` that only does the right thing on one platform and architecture is a trap - it means it's easy to write code that will e.g. pass CI on Github actions (linux/x86_64) but fail only when running on e.g. `aarch64`.

**Comment by saschagrunert** [comment]
> I think I like the number 2 the best.

I kinda like the first one. Why would you prefer options 2 over 1?

**Comment by cgwalters** [comment]
I'm good with option 1 too.
